[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_voting_contract = "8vDcMPAPjXDCy7zgNmN9u3JNTWJAvBzuwt9Lhztub82Y"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/Users/paritoshkumar/.config/solana/my-new-wallet.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
